Feature/test branch 1 (#22)
* dummy commit by changing lifecycle possible to generate diff

* Added another way to get target TF modules for PR and non-PR ways

* Testing correct branch name determination in case of push or PR events

* using newer version of branch-name

* Using new action to set GITHUB_REF_NAME

* Using GITHUB_ENV to set branch name

* TEMP: Removed source branch from git diff

* Testing additional resource cost comment on PR

* Testing infracost with azure

* Added a new aws_key_pair in TF module to see if it adds cost

* dummy commit #1

* dummy commit #2

* dummy commit #3

* dummy commit #4

* dummy commit #5

* dummy commit #6

* dummy commit #7

* TEMP: Testing if creating ec2 instance changes infracost

* Creating vm in azure tf module for testing cost

* Removed all temporarily added resources

* Removed PR TEMPLATE folder

* Added support for TF plan PR comment, plan status and TF apply

* Commented Pyaction Usage jobs

* dummy commit

* Removed bucket-two from aws-tfstate module

Co-authored-by: Charan, Varun <varun.charan@barco.com>

diff --git a/.github/workflows/terraform-modules-workflow.yaml b/.github/workflows/terraform-modules-workflow.yaml
--- a/.github/workflows/terraform-modules-workflow.yaml
+++ b/.github/workflows/terraform-modules-workflow.yaml
@@ -7,15 +7,14 @@ on:
       - feature/*
       # Meant for DEVOPS-* tickets
       - hotfix/*
+      - master
     # DO NOT trigger workflow run on updates to templates
     paths-ignore:
       - '.github/ISSUE_TEMPLATE/**'
-      - '.github/PULL_REQUEST_TEMPLATE/**'
       - '.github/pull_request_template.md'
   pull_request:
     types:
       - opened
-      - closed
       - synchronize
     branches:
       # Meant for running after PR merged on master
@@ -23,53 +22,52 @@ on:
     # DO NOT trigger workflow run on updates to templates
     paths-ignore:
       - '.github/ISSUE_TEMPLATE/**'
-      - '.github/PULL_REQUEST_TEMPLATE/**'
       - '.github/pull_request_template.md'
   # For manual trigger of job, if required. Avoids need to use dummy commits to initiate workflow.Applicable to master branch only since for it, source tag is picked from Git tags and not from Commit hash as is the case for dev branches.
   workflow_dispatch:
 
 jobs:
-  # U S I N G   P Y A C T I O N
-  exec_command:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Test pyaction with exec devops cli command
-      uses: varun-charan/pyaction@v0.5.0
-      with:
-        index_url_pip: ${{ secrets.INDEX_URL_PIP }}
-        command: "exec"
-        args: "python3 --version"
+  # # U S I N G   P Y A C T I O N
+  # exec_command:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - name: Test pyaction with exec devops cli command
+  #     uses: varun-charan/pyaction@v0.5.0
+  #     with:
+  #       index_url_pip: ${{ secrets.INDEX_URL_PIP }}
+  #       command: "exec"
+  #       args: "python3 --version"
   
-  non_exec_command:
-    runs-on: ubuntu-latest
-    outputs:
-      stdout: ${{ steps.pyaction_non_exec_cmd.outputs.stdout }}
-    steps:
-    - name: Test pyaction with non-exec devops cli command
-      id: pyaction_non_exec_cmd
-      uses: varun-charan/pyaction@v0.5.0
-      env:
-        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
-        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
-      with:
-        devops_version: "v0.5.0"
-        index_url_pip: ${{ secrets.INDEX_URL_PIP }}
-        export_list: "VAULT_ADDR=${{ env.VAULT_ADDR }}, VAULT_TOKEN=${{ env.VAULT_TOKEN }}"
-        command: "vault"
-        subcommand: "get"
-        args: "prd/devops/newreleases automation_api_key"
+  # non_exec_command:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     stdout: ${{ steps.pyaction_non_exec_cmd.outputs.stdout }}
+  #   steps:
+  #   - name: Test pyaction with non-exec devops cli command
+  #     id: pyaction_non_exec_cmd
+  #     uses: varun-charan/pyaction@v0.5.0
+  #     env:
+  #       VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
+  #       VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
+  #     with:
+  #       devops_version: "v0.5.0"
+  #       index_url_pip: ${{ secrets.INDEX_URL_PIP }}
+  #       export_list: "VAULT_ADDR=${{ env.VAULT_ADDR }}, VAULT_TOKEN=${{ env.VAULT_TOKEN }}"
+  #       command: "vault"
+  #       subcommand: "get"
+  #       args: "prd/devops/newreleases automation_api_key"
 
-  test_vault_output:
-    runs-on: ubuntu-latest
-    needs: [ non_exec_command ]
-    steps:
-      - name: Test if pyaction vault command returned correct output
-        shell: bash
-        run: |
-          echo "::add-mask::$API_KEY"
-          curl --location --request GET 'https://api.newreleases.io/v1/projects' --header 'X-Key: ${{ env.API_KEY }}'
-        env:
-          API_KEY: ${{ needs.non_exec_command.outputs.stdout }}
+  # test_vault_output:
+  #   runs-on: ubuntu-latest
+  #   needs: [ non_exec_command ]
+  #   steps:
+  #     - name: Test if pyaction vault command returned correct output
+  #       shell: bash
+  #       run: |
+  #         echo "::add-mask::$API_KEY"
+  #         curl --location --request GET 'https://api.newreleases.io/v1/projects' --header 'X-Key: ${{ env.API_KEY }}'
+  #       env:
+  #         API_KEY: ${{ needs.non_exec_command.outputs.stdout }}
 
   # T E R R A F O R M   C I C D 
   get_target_modules:
@@ -79,6 +77,12 @@ jobs:
     steps:
       - name: Checkout application GitHub repo
         uses: actions/checkout@v3
+
+      - name: Get correct branch name in case of push or pull_request events
+        id: branch-name
+        uses: tj-actions/branch-names@v6
+
+      - run: echo "BRANCH_NAME=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV
       
       - name: Get target TF modules
         id: get_target_tf_modules
@@ -86,12 +90,12 @@ jobs:
         run: |
           git fetch origin master
 
-          if [ -z `git diff --dirstat=files,0 --name-only $GITHUB_REF_NAME origin/master | grep -v .github` ]; then
+          if [ -z `git diff --dirstat=files,0 --name-only origin/master | grep -v .github` ]; then
             CHANGED_TF_MODULES_JSON=$(printf '[]\n')
 
             echo "TF Modules JSON: " $CHANGED_TF_MODULES_JSON
           else
-            CHANGED_TF_MODULES=`git diff --dirstat=files,0 --name-only $GITHUB_REF_NAME origin/master | sed -E 's/^[ 0-9.]+% //g' | cut -d '/' -f1 | grep -v .github | uniq | sort`
+            CHANGED_TF_MODULES=`git diff --dirstat=files,0 --name-only origin/master | sed -E 's/^[ 0-9.]+% //g' | cut -d '/' -f1 | grep -v .github | uniq | sort`
 
             echo "TF Modules: " $CHANGED_TF_MODULES
 
@@ -124,7 +128,7 @@ jobs:
 
     - name: Terraform Format
       id: fmt
-      run: terraform -chdir=${{ matrix.TF_MODULE }} fmt -check
+      run: terraform -chdir=${{ matrix.TF_MODULE }} fmt -check -recursive -diff
 
     - name: Terraform Init
       id: init
@@ -183,17 +187,48 @@ jobs:
     #   env:
     #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
     #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-    #     AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
     #   id: plan
     #   run: |
     #     echo "::add-mask::$AWS_ACCESS_KEY_ID"
     #     echo "::add-mask::$AWS_SECRET_ACCESS_KEY"
-    #     echo "::add-mask::$AWS_SESSION_TOKEN"
     #     export AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
     #     export AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
-    #     export AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}
     #     terraform -chdir=${{ matrix.TF_MODULE }} plan -var-file=.ci/tfplan.tfvars
-    #   continue-on-error: false
+    #   continue-on-error: true
+  
+    # - name: Update Pull Request
+    #   uses: actions/github-script@v6
+    #   if: github.event_name == 'pull_request'
+    #   env:
+    #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+    #   with:
+    #     github-token: ${{ secrets.GITHUB_TOKEN }}
+    #     script: |
+    #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+    #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+    #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+    #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+
+    #       <details><summary>Show Plan</summary>
+
+    #       \`\`\`\n
+    #       ${process.env.PLAN}
+    #       \`\`\`
+
+    #       </details>
+
+    #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+
+    #       github.rest.issues.createComment({
+    #         issue_number: context.issue.number,
+    #         owner: context.repo.owner,
+    #         repo: context.repo.repo,
+    #         body: output
+    #       })
+
+    # - name: Terraform Plan Status
+    #   if: steps.plan.outcome == 'failure'
+    #   run: exit 1
 
   perform_security_scan:
     needs: [ get_target_modules ]
@@ -214,3 +249,17 @@ jobs:
       target_dirs: ${{ needs.get_target_modules.outputs.tf_modules }}
     secrets:
       infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}
+
+  # run_terraform_apply:
+  #   needs: [get_target_modules, static-analysis, perform_security_scan, calculate_infra_cost]
+  #   runs-on: ubuntu-latest
+  #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+  #   env:
+  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #   strategy:
+  #     matrix:
+  #       TF_MODULE: "${{ fromJson(needs.get_target_modules.outputs.tf_modules) }}"
+  #   steps:
+  #     - run: terraform -chdir=${{ matrix.TF_MODULE }} apply -auto-approve -var-file=.ci/tfplan.tfvars
+  
