Added support for TF plan PR comment, plan status and TF apply

diff --git a/.github/workflows/terraform-modules-workflow.yaml b/.github/workflows/terraform-modules-workflow.yaml
--- a/.github/workflows/terraform-modules-workflow.yaml
+++ b/.github/workflows/terraform-modules-workflow.yaml
@@ -128,7 +128,7 @@ jobs:
 
     - name: Terraform Format
       id: fmt
-      run: terraform -chdir=${{ matrix.TF_MODULE }} fmt -check
+      run: terraform -chdir=${{ matrix.TF_MODULE }} fmt -check -recursive -diff
 
     - name: Terraform Init
       id: init
@@ -187,17 +187,48 @@ jobs:
     #   env:
     #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
     #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-    #     AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
     #   id: plan
     #   run: |
     #     echo "::add-mask::$AWS_ACCESS_KEY_ID"
     #     echo "::add-mask::$AWS_SECRET_ACCESS_KEY"
-    #     echo "::add-mask::$AWS_SESSION_TOKEN"
     #     export AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
     #     export AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
-    #     export AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}
     #     terraform -chdir=${{ matrix.TF_MODULE }} plan -var-file=.ci/tfplan.tfvars
-    #   continue-on-error: false
+    #   continue-on-error: true
+  
+    # - name: Update Pull Request
+    #   uses: actions/github-script@v6
+    #   if: github.event_name == 'pull_request'
+    #   env:
+    #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+    #   with:
+    #     github-token: ${{ secrets.GITHUB_TOKEN }}
+    #     script: |
+    #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+    #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+    #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+    #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+
+    #       <details><summary>Show Plan</summary>
+
+    #       \`\`\`\n
+    #       ${process.env.PLAN}
+    #       \`\`\`
+
+    #       </details>
+
+    #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+
+    #       github.rest.issues.createComment({
+    #         issue_number: context.issue.number,
+    #         owner: context.repo.owner,
+    #         repo: context.repo.repo,
+    #         body: output
+    #       })
+
+    # - name: Terraform Plan Status
+    #   if: steps.plan.outcome == 'failure'
+    #   run: exit 1
 
   perform_security_scan:
     needs: [ get_target_modules ]
@@ -218,3 +249,16 @@ jobs:
       target_dirs: ${{ needs.get_target_modules.outputs.tf_modules }}
     secrets:
       infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}
+
+  # run_terraform_apply:
+  #   needs: [get_target_modules, static-analysis, perform_security_scan, calculate_infra_cost]
+  #   runs-on: ubuntu-latest
+  #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+  #   env:
+  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #   strategy:
+  #     matrix:
+  #       TF_MODULE: "${{ fromJson(needs.get_target_modules.outputs.tf_modules) }}"
+  #   steps:
+  #     - run: terraform -chdir=${{ matrix.TF_MODULE }} apply -auto-approve -var-file=.ci/tfplan.tfvars
